/* codes: {
	'0': 'RCWSuccess',
	'50': 'RCWInvalidParams',
	'1000': 'RCWUnknown',
	'1001': 'RCWIncorrectCmd',
	'1002': 'RCWUnknownCmd',
	'101': 'RCWInvalidTicketStepID',
	'102': 'RCWInvalidQualityMark',
	'103': 'RCWIntervalBusy',
	'104': 'RCWInvalidPeriod',
	'105': 'RCWInvalidPriorityID',
	'106': 'RCWInvalidRatingID',
	'107': 'RCWInvalidServiceID',
	'108': 'RCWInvalidSourceKind',
	'109': 'RCWInvalidWorkplaceID',
	'110': 'RCWInvalidWorkuserID',
	'111': 'RCWInvalidQualityMarkReason',
	'112': 'RCWInvalidState',
	'113': 'RCWInvalidCustID',
	'114': 'RCWIncorrectLogin',
	'115': 'RCWIncorrectPass',
	'116': 'RCWInvalidBranchID',
	'117': 'RCWInvalidLat',
	'118': 'RCWInvalidLon',
	'119': 'RCWInvalidCRTName',
	'120': 'RCWInvalidCRTCondition',
	'121': 'RCWInvalidCRTType',
	'122': 'RCWDuplicateCRT',
	'123': 'RCWInvalidCRTID',
	'124': 'RCWNoCRTID',
	'125': 'RCWEmptyRegion',
	'126': 'RCWEmptyCRT',
	'127': 'RCWIncorrectCustCode',
	'128': 'RCWInvalidLanguageID',
	'129': 'RCWInvalidCount',
	'130': 'RCWMismatchWorkplaceID',
	'131': 'RCWMismatchWorkuserID',
	'132': 'RCWInvalidPIN',
	'136': 'RCWSMSPhoneNumberISUse',
	'145': 'RCWRegisterTicketsLimit',
	'820': 'JSErrNoConnect',
	'821': 'JSErrServerUnavailable',
	'822': 'JSErrDataIsNull',
	'823': 'JSErrCommandUndefined',
	'824': 'JSErrMenuIsNull',
	'825': 'JSErrCustCodeInvalid',
	'826': 'JSErrMissingLangPack',
	'827': 'JSErrIntervalsGettingError',
	'828': 'JSErrMissingCustomerByTicket',
	'829': 'JSErrMissingWorkuserByID',
	'835': 'JSErrRestartServer',
	'830': 'JSErrMissingJSONLang',
	'831': 'JSErrMissingPIN',
	'832': 'JSErrSRByPINLate',
	'833': 'JSErrSRByPINOtherDay',
	'834': 'JSErrSRByPINAlready',
	'836': 'JSErrSRByPINEarly',
	'1': 'PrintErrStatusNotDefined',
	'2': 'PrintErrTypeNotDefined',
	'3': 'PrintErrWrongID',
	'4': 'PrintErrWrongResponse',
	'5': 'PrintErrNoConnection',
	'6': 'PrintErrDataTransferImpossible',
	'7': 'PrintErrNoPaper',
	'8': 'PrintErrDamagedPaper',
	'9': 'PrintErrUnknown',
	'10': 'PrintErrCapIsOpened'
},
messages: {
	'RCWSuccess': 'The operation completed successfully!',
	'RCWInvalidParams': 'Invalid parameters.',
	'RCWUnknown': 'Unknown error.',
	'RCWIncorrectCmd': 'Unknown command format. Check the format of the transmitted command.',
	'RCWUnknownCmd': 'Unknown command. Check the command sent in the "command" parameter.',
	'RCWInvalidTicketStepID': 'Invalid TicketStep ID.',
	'RCWInvalidQualityMark': 'Incorrect quality mark.',
	'RCWIntervalBusy': 'Interval is busy.',
	'RCWInvalidPeriod': 'Incorrect period.',
	'RCWInvalidPriorityID': 'Incorrect priority ID.',
	'RCWInvalidRatingID': 'Incorrect rating ID.',
	'RCWInvalidServiceID': 'Incorrect service ID.',
	'RCWInvalidSourceKind': 'Invalid source.',
	'RCWInvalidWorkplaceID': 'Incorrect workplace ID.',
	'RCWInvalidWorkuserID': 'Incorrect workuser ID.',
	'RCWInvalidQualityMarkReason': 'Incorrect quality mark reason.',
	'RCWInvalidState': 'Incorrect state.',
	'RCWInvalidCustID': 'Incorrect customer ID.',
	'RCWIncorrectLogin': 'Incorrect login.',
	'RCWIncorrectPass': 'Incorrect password.',
	'RCWInvalidBranchID': 'Incorrect branch ID.',
	'RCWInvalidLat': 'Incorrect latitude.',
	'RCWInvalidLon': 'Incorrect longitude.',
	'RCWInvalidCRTName': 'Incorrect critical point name.',
	'RCWInvalidCRTCondition': 'Incorrect critical point condition.',
	'RCWInvalidCRTType': 'Incorrect critical point type.',
	'RCWDuplicateCRT': 'Duplicate critical point.',
	'RCWInvalidCRTID': 'Incorrect critical point ID.',
	'RCWNoCRTID': 'Missing critical point ID.',
	'RCWEmptyRegion': 'Empty region.',
	'RCWEmptyCRT': 'Empty critical point.',
	'RCWIncorrectCustCode': 'Incorrect PIN.',
	'RCWInvalidLanguageID': 'Invalid language ID.',
	'RCWInvalidCount': 'Invalid count of services.',
	'RCWMismatchWorkplaceID': 'Mismatch workplace ID.',
	'RCWMismatchWorkuserID': 'Mismatch worker ID.',
	'RCWInvalidPIN': 'Incorrect PIN.',
	'RCWRegisterTicketsLimit': 'Tickets limit on this service has been reached.',
	'JSErrNoConnect': 'No connection to server.',
	'JSErrServerUnavailable': 'Server is unavailable.',
	'JSErrDataIsNull': 'Invalid request or no data.',
	'JSErrCommandUndefined': 'Command is undefined.',
	'JSErrMenuIsNull': 'Menu section is missing.',
	'JSErrCustCodeInvalid': 'Incorrect PIN.',
	'JSErrMissingLangPack': 'Failed to load language pack.',
	'JSErrIntervalsGettingError': 'Failed to load intervals.',
	'JSErrMissingCustomerByTicket': 'There is no user on this ticket.',
	'JSErrMissingWorkuserByID': 'There is no workuser on this ID.',
	'JSErrRestartServer': 'Server data corrupted.',
	'JSErrMissingJSONLang': 'Unknown error.',
	'JSErrMissingPIN': 'Unknown error.',
	'JSErrSRByPINLate': 'Unknown error.',
	'JSErrSRByPINOtherDay': 'Unknown error.',
	'JSErrSRByPINAlready': 'Unknown error.'
}
*/